### ISSUE TITLE
点击网络会报错，请求帮助！

### ISSUE THREAD

**Issue by zhxse7en** [bihell/nezha-docker#1]
![image](https://github.com/bihell/nezha-docker/assets/17829758/75d0507b-79d0-4d70-8541-a1138a4306d0)

![image](https://github.com/bihell/nezha-docker/assets/17829758/3da4ca02-52ad-4eef-91fb-cd28825d63dc)

**Comment by bihell** [comment]
如果你没配置网络监控就会报这个错误，如果配置了，那需要等一会儿再去看。
